name: 'Scope for Maven'
author: 'Daniel Rodriguez <@drodriguezhdez> | UndefinedLabs'
description: 'Setup Scope for Maven to improve your MTTR of your broken builds and manage your flaky tests.'
inputs:
  dsn:
    description: 'Scope DSN'
    required: true
  execute-command:
    description: 'Flag to indicate if the command must be executed. default: true'
    default: 'true'
    required: true
  command:
    description: 'Command to execute for your test phase. default: mvn verify'
    default: 'mvn verify'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'purple'